// City catalog: [name, country, IANA zone, short code, landmark key?]
// Anything not listed here is still reachable through Intl.supportedValuesOf('timeZone').
window.CITY_CATALOG = [
  // North America
  ['San Francisco', 'United States', 'America/Los_Angeles', 'SF', 'goldengate'],
  ['Los Angeles', 'United States', 'America/Los_Angeles', 'LA'],
  ['San Diego', 'United States', 'America/Los_Angeles', 'SAN'],
  ['Seattle', 'United States', 'America/Los_Angeles', 'SEA', 'spaceneedle'],
  ['Portland', 'United States', 'America/Los_Angeles', 'PDX'],
  ['Las Vegas', 'United States', 'America/Los_Angeles', 'LAS'],
  ['Phoenix', 'United States', 'America/Phoenix', 'PHX'],
  ['Denver', 'United States', 'America/Denver', 'DEN'],
  ['Salt Lake City', 'United States', 'America/Denver', 'SLC'],
  ['Chicago', 'United States', 'America/Chicago', 'CHI'],
  ['Austin', 'United States', 'America/Chicago', 'AUS'],
  ['Dallas', 'United States', 'America/Chicago', 'DAL'],
  ['Houston', 'United States', 'America/Chicago', 'HOU'],
  ['Minneapolis', 'United States', 'America/Chicago', 'MSP'],
  ['New York', 'United States', 'America/New_York', 'NYC', 'empirestate'],
  ['Boston', 'United States', 'America/New_York', 'BOS'],
  ['Washington DC', 'United States', 'America/New_York', 'DC'],
  ['Atlanta', 'United States', 'America/New_York', 'ATL'],
  ['Miami', 'United States', 'America/New_York', 'MIA'],
  ['Detroit', 'United States', 'America/Detroit', 'DTW'],
  ['Anchorage', 'United States', 'America/Anchorage', 'ANC'],
  ['Honolulu', 'United States', 'Pacific/Honolulu', 'HNL'],
  ['Toronto', 'Canada', 'America/Toronto', 'TOR', 'cntower'],
  ['Montreal', 'Canada', 'America/Toronto', 'MTL'],
  ['Ottawa', 'Canada', 'America/Toronto', 'OTT'],
  ['Vancouver', 'Canada', 'America/Vancouver', 'VAN'],
  ['Calgary', 'Canada', 'America/Edmonton', 'YYC'],
  ['Halifax', 'Canada', 'America/Halifax', 'HFX'],
  ['St. John\'s', 'Canada', 'America/St_Johns', 'YYT'],
  ['Mexico City', 'Mexico', 'America/Mexico_City', 'MEX'],
  ['Guadalajara', 'Mexico', 'America/Mexico_City', 'GDL'],
  ['Monterrey', 'Mexico', 'America/Monterrey', 'MTY'],
  // Latin America & Caribbean
  ['Panama City', 'Panama', 'America/Panama', 'PTY'],
  ['San José', 'Costa Rica', 'America/Costa_Rica', 'SJO'],
  ['Guatemala City', 'Guatemala', 'America/Guatemala', 'GUA'],
  ['Havana', 'Cuba', 'America/Havana', 'HAV'],
  ['San Juan', 'Puerto Rico', 'America/Puerto_Rico', 'SJU'],
  ['Kingston', 'Jamaica', 'America/Jamaica', 'KIN'],
  ['Bogotá', 'Colombia', 'America/Bogota', 'BOG'],
  ['Medellín', 'Colombia', 'America/Bogota', 'MDE'],
  ['Lima', 'Peru', 'America/Lima', 'LIM'],
  ['Quito', 'Ecuador', 'America/Guayaquil', 'UIO'],
  ['Caracas', 'Venezuela', 'America/Caracas', 'CCS'],
  ['Santiago', 'Chile', 'America/Santiago', 'SCL'],
  ['Buenos Aires', 'Argentina', 'America/Argentina/Buenos_Aires', 'BUE'],
  ['Montevideo', 'Uruguay', 'America/Montevideo', 'MVD'],
  ['São Paulo', 'Brazil', 'America/Sao_Paulo', 'SAO'],
  ['Rio de Janeiro', 'Brazil', 'America/Sao_Paulo', 'RIO'],
  ['Brasília', 'Brazil', 'America/Sao_Paulo', 'BSB'],
  // Europe
  ['London', 'United Kingdom', 'Europe/London', 'LDN', 'bigben'],
  ['Manchester', 'United Kingdom', 'Europe/London', 'MAN'],
  ['Edinburgh', 'United Kingdom', 'Europe/London', 'EDI'],
  ['Dublin', 'Ireland', 'Europe/Dublin', 'DUB'],
  ['Lisbon', 'Portugal', 'Europe/Lisbon', 'LIS'],
  ['Porto', 'Portugal', 'Europe/Lisbon', 'OPO'],
  ['Madrid', 'Spain', 'Europe/Madrid', 'MAD'],
  ['Barcelona', 'Spain', 'Europe/Madrid', 'BCN'],
  ['Paris', 'France', 'Europe/Paris', 'PAR', 'eiffel'],
  ['Brussels', 'Belgium', 'Europe/Brussels', 'BRU'],
  ['Amsterdam', 'Netherlands', 'Europe/Amsterdam', 'AMS'],
  ['Berlin', 'Germany', 'Europe/Berlin', 'BER'],
  ['Munich', 'Germany', 'Europe/Berlin', 'MUC'],
  ['Frankfurt', 'Germany', 'Europe/Berlin', 'FRA'],
  ['Hamburg', 'Germany', 'Europe/Berlin', 'HAM'],
  ['Zurich', 'Switzerland', 'Europe/Zurich', 'ZRH'],
  ['Geneva', 'Switzerland', 'Europe/Zurich', 'GVA'],
  ['Vienna', 'Austria', 'Europe/Vienna', 'VIE'],
  ['Milan', 'Italy', 'Europe/Rome', 'MIL'],
  ['Rome', 'Italy', 'Europe/Rome', 'ROM'],
  ['Copenhagen', 'Denmark', 'Europe/Copenhagen', 'CPH'],
  ['Oslo', 'Norway', 'Europe/Oslo', 'OSL'],
  ['Stockholm', 'Sweden', 'Europe/Stockholm', 'STO'],
  ['Helsinki', 'Finland', 'Europe/Helsinki', 'HEL'],
  ['Tallinn', 'Estonia', 'Europe/Tallinn', 'TLL'],
  ['Riga', 'Latvia', 'Europe/Riga', 'RIX'],
  ['Vilnius', 'Lithuania', 'Europe/Vilnius', 'VNO'],
  ['Warsaw', 'Poland', 'Europe/Warsaw', 'WAW'],
  ['Kraków', 'Poland', 'Europe/Warsaw', 'KRK'],
  ['Prague', 'Czechia', 'Europe/Prague', 'PRG'],
  ['Budapest', 'Hungary', 'Europe/Budapest', 'BUD'],
  ['Bucharest', 'Romania', 'Europe/Bucharest', 'BUH'],
  ['Sofia', 'Bulgaria', 'Europe/Sofia', 'SOF'],
  ['Belgrade', 'Serbia', 'Europe/Belgrade', 'BEG'],
  ['Zagreb', 'Croatia', 'Europe/Zagreb', 'ZAG'],
  ['Athens', 'Greece', 'Europe/Athens', 'ATH'],
  ['Kyiv', 'Ukraine', 'Europe/Kyiv', 'KYV'],
  ['Istanbul', 'Türkiye', 'Europe/Istanbul', 'IST'],
  ['Moscow', 'Russia', 'Europe/Moscow', 'MOW'],
  ['Reykjavík', 'Iceland', 'Atlantic/Reykjavik', 'REK'],
  // Middle East
  ['Dubai', 'UAE', 'Asia/Dubai', 'DXB', 'burj'],
  ['Abu Dhabi', 'UAE', 'Asia/Dubai', 'AUH'],
  ['Riyadh', 'Saudi Arabia', 'Asia/Riyadh', 'RUH', 'kingdom'],
  ['Jeddah', 'Saudi Arabia', 'Asia/Riyadh', 'JED'],
  ['Doha', 'Qatar', 'Asia/Qatar', 'DOH'],
  ['Kuwait City', 'Kuwait', 'Asia/Kuwait', 'KWI'],
  ['Manama', 'Bahrain', 'Asia/Bahrain', 'BAH'],
  ['Muscat', 'Oman', 'Asia/Muscat', 'MCT'],
  ['Tel Aviv', 'Israel', 'Asia/Jerusalem', 'TLV'],
  ['Amman', 'Jordan', 'Asia/Amman', 'AMM'],
  ['Beirut', 'Lebanon', 'Asia/Beirut', 'BEY'],
  ['Tehran', 'Iran', 'Asia/Tehran', 'THR'],
  ['Baghdad', 'Iraq', 'Asia/Baghdad', 'BGW'],
  // Africa
  ['Cairo', 'Egypt', 'Africa/Cairo', 'CAI'],
  ['Casablanca', 'Morocco', 'Africa/Casablanca', 'CAS'],
  ['Tunis', 'Tunisia', 'Africa/Tunis', 'TUN'],
  ['Lagos', 'Nigeria', 'Africa/Lagos', 'LOS'],
  ['Abuja', 'Nigeria', 'Africa/Lagos', 'ABV'],
  ['Accra', 'Ghana', 'Africa/Accra', 'ACC'],
  ['Dakar', 'Senegal', 'Africa/Dakar', 'DKR'],
  ['Nairobi', 'Kenya', 'Africa/Nairobi', 'NBO'],
  ['Addis Ababa', 'Ethiopia', 'Africa/Addis_Ababa', 'ADD'],
  ['Kampala', 'Uganda', 'Africa/Kampala', 'KLA'],
  ['Kigali', 'Rwanda', 'Africa/Kigali', 'KGL'],
  ['Dar es Salaam', 'Tanzania', 'Africa/Dar_es_Salaam', 'DAR'],
  ['Johannesburg', 'South Africa', 'Africa/Johannesburg', 'JNB'],
  ['Cape Town', 'South Africa', 'Africa/Johannesburg', 'CPT'],
  // South Asia
  ['Karachi', 'Pakistan', 'Asia/Karachi', 'KHI'],
  ['Lahore', 'Pakistan', 'Asia/Karachi', 'LHE'],
  ['Islamabad', 'Pakistan', 'Asia/Karachi', 'ISB'],
  ['Mumbai', 'India', 'Asia/Kolkata', 'BOM'],
  ['Delhi', 'India', 'Asia/Kolkata', 'DEL'],
  ['Hyderabad', 'India', 'Asia/Kolkata', 'HYD', 'charminar'],
  ['Bengaluru', 'India', 'Asia/Kolkata', 'BLR'],
  ['Chennai', 'India', 'Asia/Kolkata', 'MAA'],
  ['Pune', 'India', 'Asia/Kolkata', 'PNQ'],
  ['Kolkata', 'India', 'Asia/Kolkata', 'CCU'],
  ['Ahmedabad', 'India', 'Asia/Kolkata', 'AMD'],
  ['Kathmandu', 'Nepal', 'Asia/Kathmandu', 'KTM'],
  ['Colombo', 'Sri Lanka', 'Asia/Colombo', 'CMB'],
  ['Dhaka', 'Bangladesh', 'Asia/Dhaka', 'DAC'],
  ['Kabul', 'Afghanistan', 'Asia/Kabul', 'KBL'],
  ['Tashkent', 'Uzbekistan', 'Asia/Tashkent', 'TAS'],
  ['Almaty', 'Kazakhstan', 'Asia/Almaty', 'ALA'],
  // East & Southeast Asia
  ['Bangkok', 'Thailand', 'Asia/Bangkok', 'BKK'],
  ['Ho Chi Minh City', 'Vietnam', 'Asia/Ho_Chi_Minh', 'SGN'],
  ['Hanoi', 'Vietnam', 'Asia/Ho_Chi_Minh', 'HAN'],
  ['Kuala Lumpur', 'Malaysia', 'Asia/Kuala_Lumpur', 'KUL'],
  ['Singapore', 'Singapore', 'Asia/Singapore', 'SIN', 'marinabay'],
  ['Jakarta', 'Indonesia', 'Asia/Jakarta', 'JKT'],
  ['Bali', 'Indonesia', 'Asia/Makassar', 'DPS'],
  ['Manila', 'Philippines', 'Asia/Manila', 'MNL'],
  ['Hong Kong', 'China', 'Asia/Hong_Kong', 'HKG'],
  ['Shanghai', 'China', 'Asia/Shanghai', 'SHA', 'pearl'],
  ['Beijing', 'China', 'Asia/Shanghai', 'BJS'],
  ['Shenzhen', 'China', 'Asia/Shanghai', 'SZX'],
  ['Taipei', 'Taiwan', 'Asia/Taipei', 'TPE'],
  ['Seoul', 'South Korea', 'Asia/Seoul', 'SEL'],
  ['Tokyo', 'Japan', 'Asia/Tokyo', 'TYO', 'tokyotower'],
  ['Osaka', 'Japan', 'Asia/Tokyo', 'OSA'],
  // Oceania
  ['Perth', 'Australia', 'Australia/Perth', 'PER'],
  ['Adelaide', 'Australia', 'Australia/Adelaide', 'ADL'],
  ['Brisbane', 'Australia', 'Australia/Brisbane', 'BNE'],
  ['Sydney', 'Australia', 'Australia/Sydney', 'SYD', 'opera'],
  ['Melbourne', 'Australia', 'Australia/Melbourne', 'MEL'],
  ['Auckland', 'New Zealand', 'Pacific/Auckland', 'AKL'],
  ['Wellington', 'New Zealand', 'Pacific/Auckland', 'WLG'],
  ['Fiji', 'Fiji', 'Pacific/Fiji', 'SUV'],
  // Utility
  ['UTC', 'Coordinated Universal Time', 'UTC', 'UTC'],
];
