import {useEffect,useRef} from 'react';
import {ArrowRight} from 'lucide-react';
import SiteNav from '@/components/SiteNav';
import SiteFooter from '@/components/SiteFooter';
import SEOHead from '@/components/SEOHead';
import {getHomepageSEO} from '@/lib/seo';
import {initializeMeridian} from '@/lib/meridianExperience';
import '@/styles/meridian.css';
export default function LandingPage(){
const root=useRef(null);
useEffect(()=>initializeMeridian(root.current),[]);
return <div className="meridian-home" ref={root}><SEOHead {...getHomepageSEO()}/><SiteNav/>
<main id="main-content">
<div className="shell"><section className="hero">
<div className="hero-content"><h1>Great work.<br/><em>No borders.</em></h1><p className="hero-copy">Your next great collaboration could be a world away. Make the distance feel smaller.</p><a className="primary" href="#planner">Find your shared rhythm <ArrowRight aria-hidden="true" /></a><p className="caption">Meeting times. Currency estimates. Invoices.<br/>A free toolkit for working together, anywhere.</p></div>
<figure className="hero-art-wrap"><div className="picture-frame"><img className="hero-art" src="/meridian/meridian-finished-hero.png" width="1536" height="1024" alt="A complete sculpted paper atlas with forest-green continents and delicate gold connections" fetchPriority="high" /><div className="picture-light" aria-hidden="true"></div><svg className="atlas-routes" viewBox="0 0 1000 667" aria-hidden="true"><path className="atlas-route" d="M366 365 Q520 190 700 302"/><path className="atlas-route second" d="M536 307 Q620 230 700 302"/><circle className="atlas-node" cx="366" cy="365" r="4"/><circle className="atlas-node second" cx="700" cy="302" r="4"/></svg></div><figcaption><span>A world of possibilities.</span><span>A moment to connect.</span></figcaption></figure>
<div className="hero-bottom"><span>Thoughtfully made for work across borders.</span><a href="#rhythm">Explore together <svg><path d="M10 2v16m-5-5 5 5 5-5"/></svg></a></div>
</section><nav className="editorial-tools" aria-label="Quick access"><a href="#planner">Meeting planner <ArrowRight aria-hidden="true" /></a><a href="/currency-converter">Currency converter <ArrowRight aria-hidden="true" /></a><a href="/invoice">Invoice builder <ArrowRight aria-hidden="true" /></a></nav></div>
<section className="dark-section" id="rhythm"><div className="shell"><div className="dark-heading"><h2>A city changes.<br/>Your rhythm stays.</h2><p>Morning in one city. Afternoon in another.<br/>Find a shared moment that respects everyone’s day.</p></div>
<div className="city-tabs" aria-label="Choose a team"><button data-group="atlantic" aria-pressed="true">Across the Atlantic</button><button data-group="asia" aria-pressed="false">Europe to Asia</button><button data-group="pacific" aria-pressed="false">Across the Pacific</button></div><div className="city-readout" data-clock-row></div>
<div className="day-band"><div className="band-title">Bring your day into focus.<small>Slide through a day, together.</small></div><div><div className="slider-head"><label htmlFor="meridian-day" data-date-label></label><output data-utc></output></div><input className="range" id="meridian-day" type="range" min="0" max="95" defaultValue="52" aria-label="Time of day in 15-minute steps" /><div className="time-ticks"><span>00:00 UTC</span><span>06:00</span><span>12:00</span><span>18:00</span><span>23:45</span></div></div></div></div></section>
<div className="shell"><section className="story" id="tools"><h2>Less coordination.<br/>More connection.</h2><div className="story-copy"><p>Find a meeting time that fits. Understand an amount in another currency. Put the details into an invoice. Keep the small things simple, so the work can move forward.</p><a className="secondary" href="#planner">Plan your next conversation <ArrowRight aria-hidden="true" /></a></div></section>
<div className="tool-collection">
<a className="tool-feature" href="#planner"><div><h3>Time, on your side.</h3><p>Compare local times and find room in everyone’s day.</p><span className="tool-action">Explore the meeting planner <ArrowRight aria-hidden="true" /></span></div><div className="tool-visual time-visual" aria-hidden="true"><span>NEW YORK<b>09:00</b></span><i></i><span>LONDON<b>14:00</b></span><small>One moment. Two perspectives.</small></div></a>
<a className="tool-feature" href="/currency-converter"><div><h3>A clearer exchange.</h3><p>Put an international amount into a currency you know.</p><span className="tool-action">Open currency converter <ArrowRight aria-hidden="true" /></span></div><div className="tool-visual currency-visual" aria-hidden="true"><span>USD</span><svg viewBox="0 0 100 32"><path d="M0 10h96l-8-8M100 22H4l8 8"/></svg><span>EUR</span><small>See the amount from both sides.</small></div></a>
<a className="tool-feature" href="/invoice"><div><h3>The details, together.</h3><p>Bring your work, rates and client details into one invoice.</p><span className="tool-action">Open invoice builder <ArrowRight aria-hidden="true" /></span></div><div className="tool-visual invoice-visual" aria-hidden="true"><span>INVOICE</span><div><i></i><i></i><i></i></div><b>Work. Ready to send.</b></div></a>
</div>
<section className="planner" id="planner"><div className="planner-heading"><h2>Make room<br/>for everyone.</h2><p>Choose a date, gather your team and find a time. Every city stays in sync.</p></div><div className="planner-surface"><div className="planner-controls">
<label>Your team<select name="team"><option value="atlantic">New York · London · Berlin</option><option value="asia">London · Dubai · Singapore</option><option value="pacific">Los Angeles · Tokyo · Sydney</option></select></label>
<div className="control-pair"><label>Meeting date · UTC<input type="date" name="meeting-date" required min="2020-01-01" max="2100-12-31" /></label><label>Meeting length<select name="duration"><option value="30">30 minutes</option><option value="60">60 minutes</option><option value="90">90 minutes</option></select></label></div>
<label>Start time · <output data-utc></output><input className="range" type="range" min="0" max="95" defaultValue="52" aria-label="Meeting start time in 15-minute steps" /></label><button className="find-time">Find a shared time <ArrowRight aria-hidden="true" /></button><p className="caption">Working hours: 09:00–17:00 in each city.<br/>Local times account for daylight saving.</p></div><div className="planner-results"><div className="results-label"><span>Your shared moment</span><span data-date-label></span></div><div data-schedule></div><div className="schedule-footer"><p data-fit aria-live="polite"></p><div className="share-actions"><button className="copy">Copy local times</button><button className="calendar">Save calendar file <svg><path d="M12 3v12m-4-4 4 4 4-4M4 17v4h16v-4"/></svg></button></div></div><p className="notice" role="status" aria-live="polite"></p></div></div><p className="planner-note"><a href="/meeting-planner">Choose custom cities and working hours in the full planner →</a><br/>Calendar files save the chosen time. Review the event in your calendar before inviting your team.</p></section>
<section className="faq" id="questions"><h2>A little clarity.<br/>A better start.</h2><div><details><summary>What can I do with GlobalSync AI?<svg><path d="M12 4v16M4 12h16"/></svg></summary><p>Compare three-city teams, change your meeting date and length, find a shared time, copy local times or download a calendar file. Use the complete planner for custom cities and working hours, or explore currency, freelance rates and invoices.</p></details><details><summary>How are shared hours calculated?<svg><path d="M12 4v16M4 12h16"/></svg></summary><p>The planner checks the entire meeting against 09:00–17:00 in each city, using the selected date and each city’s time zone. Working hours here apply to every day; holidays and individual availability are not checked.</p></details><details><summary>What happens if there is no overlap?<svg><path d="M12 4v16M4 12h16"/></svg></summary><p>Some teams span too many time zones for everyone to meet during working hours. The planner tells you when no shared window exists, so you can discuss a compromise with your team.</p></details></div></section></div>
<section className="closing"><div className="shell"><h2>A smaller world.<br/><em>A bigger possibility.</em></h2><a className="primary" href="#planner">Bring your world together <ArrowRight aria-hidden="true" /></a></div></section>
</main>
<section className="shell more-tools"><h2>Your next step, made simpler.</h2><nav aria-label="More GlobalSync tools"><a href="/time-zone-converter">World clocks and time zones</a><a href="/freelancer-rate-converter">Freelancer rate calculator</a><a href="/dashboard">Open your workspace</a><a href="/blog">Guides for working globally</a></nav><form action="/dashboard"><label htmlFor="home-question">Ask about a time or currency conversion</label><div><input id="home-question" name="q" placeholder="What time is 3 PM New York in London?" required maxLength={500}/><button type="submit">Find an answer <ArrowRight aria-hidden="true"/></button></div></form></section>
<div className="shell motion-row"><button className="motion-toggle" aria-pressed="false">Pause motion</button></div><SiteFooter/></div>;
}
